Add redirects for all existing plugins to redirect to plugin site
jenkins-infra/jenkins-infra pull request #1411
Opened 2020-01-28 22:18 UTC by halkeye

In theory this will allow wiki exporter to come through, but all the rest will redirect to plugins site

2020-01-29 00:15 UTC, timja approved these changes

2020-01-29 07:54 UTC, olblak commented on dist/profile/templates/confluence/vhost.conf
> +RewriteRule "^/display/Priority\+Sorter\+Plugin$" "https://plugins.jenkins.io/PrioritySorter" [NC,L,QSA,R=301]
Are you not missing /JENKINS/ between /display and plugin name?
An exampled `https://wiki.jenkins.io/display/JENKINS/Priority+Sorter+Plugin`

2020-01-29 08:00 UTC, olblak requested changes
RewriteRule url need to be fixed, as plugin urls on wiki are not correct

2020-01-29 18:27 UTC, halkeye commented
thanks @olblak that was super dumb of me. I updated the script and generating the right urls now

2020-01-31 06:43 UTC, MarkEWaite approved these changes

2020-02-04 01:02 UTC, rtyler approved these changes
Looks good to me, puppet will need to be re-enabled on the host to deploy this

2020-02-04 07:59 UTC, olblak commented
> Looks good to me, puppet will need to be re-enabled on the host to deploy this
I don't recall or see a reason why puppet was disabled on lettuce

2020-02-04 08:01 UTC, timja commented
> > Looks good to me, puppet will need to be re-enabled on the host to deploy this
> > I don't recall or see a reason why puppet was disabled on lettuce

I think @rtyler re-enabled it, see IRC

2020-02-04 08:02 UTC, olblak approved these changes

2020-02-04 08:32 UTC, merged

2020-02-04 08:59 UTC, timja commented
I think the auto prod PR function is broken atm too