Redirect governance documents from wiki to jenkins.io
jenkins-infra/jenkins-infra pull request #1441
Opened 2020-02-26 21:33 UTC by MarkEWaite

The governance document and governance meeting pages have already migrated and are only pointers to the official jenkins.io pages.

The governance board page has been migrated to jenkins.io but does not have a pointer in the page.  This redirect avoids editing that page by redirecting to jenkins.io.

The candidacy process and election process for the Jenkins board are maintained on jenkins.io.  No need to show the user an outdated copy from the wiki.

2020-02-27 12:29 UTC, slide approved these changes

2020-02-27 12:50 UTC, oleg-nenashev requested changes
1 minor issue with anchor

2020-02-27 12:50 UTC, oleg-nenashev commented on dist/profile/templates/confluence/vhost.conf
> +RewriteRule "^/display/JENKINS/Governance\+Document$" "https://jenkins.io/project/governance/#compatibility-matters" [NC,L,QSA,R=301]
```suggestion
RewriteRule "^/display/JENKINS/Governance\+Document$" "https://jenkins.io/project/governance/" [NC,L,QSA,R=301]
```

2020-02-27 14:33 UTC, rtyler approved these changes

2020-02-27 21:56 UTC, oleg-nenashev approved these changes

2020-03-04 08:10 UTC, olblak approved these changes

2020-03-04 09:51 UTC, merged