Redirect Remote access API from wiki to jenkins.io
jenkins-infra/jenkins-infra pull request #1482
Opened 2020-05-19 15:19 UTC by zaycodes

2020-05-19 20:13 UTC, MarkEWaite approved these changes
This is the most requested page on wiki.jenkins.io based on web access logs collected for the past 90 days.  Thanks very much @zaycodes !

2020-05-20 08:11 UTC, olblak requested changes
for some reason, I can't commit my suggestion, so if you could remove the duplicated rewriteCond

2020-05-20 08:11 UTC, olblak commented on dist/profile/templates/confluence/vhost.conf
> +RewriteCond %{HTTP_USER_AGENT} !^jenkins-wiki-exporter/(.*)$
```suggestion
```
This line is duplicated

2020-05-20 13:52 UTC, zaycodes commented
> This is the most requested page on wiki.jenkins.io based on web access logs collected for the past 90 days. Thanks very much @zaycodes !

You are welcome @MarkEWaite

2020-05-25 11:22 UTC, merged