Git, Matrix Configuration Parameter Plugin & Require Upper Bounds redirection placed
jenkins-infra/jenkins-infra pull request #1486
Opened 2020-05-21 12:13 UTC by krharsh17

This PR fixes the following issues:
[#3310](https://github.com/jenkins-infra/jenkins.io/issues/3310)
[#3311](https://github.com/jenkins-infra/jenkins.io/issues/3311)
[#3313](https://github.com/jenkins-infra/jenkins.io/issues/3313)

2020-05-22 17:17 UTC, MarkEWaite requested changes
The original links in the GitHub issues mistakenly included a duplicated slash inside the URL.  That needs to be removed or the redirect won't work for most users

2020-05-22 17:17 UTC, MarkEWaite commented on dist/profile/templates/confluence/vhost.conf
> +RewriteRule "^/display/JENKINS//Matrix\+Configuration\+Parameter\+Plugin$" "https://plugins.jenkins.io/matrix-combinations-parameter/" [NE,NC,L,QSA,R=301]
Need to remove the redundant slash
```suggestion
RewriteRule "^/display/JENKINS/Matrix\+Configuration\+Parameter\+Plugin$" "https://plugins.jenkins.io/matrix-combinations-parameter/" [NE,NC,L,QSA,R=301]
```

2020-05-22 17:17 UTC, MarkEWaite commented on dist/profile/templates/confluence/vhost.conf
> +RewriteRule "^/display/JENKINS//How\+to\+fix\+RequireUpperBoundDeps$" "https://www.jenkins.io/doc/developer/plugin-development/updating-parent/#understanding-requireupperbounddeps-failures-and-fixes"
Need to remove extra '/' here
```suggestion
RewriteRule "^/display/JENKINS/How\+to\+fix\+RequireUpperBoundDeps$" "https://www.jenkins.io/doc/developer/plugin-development/updating-parent/#understanding-requireupperbounddeps-failures-and-fixes" [NE,NC,L,QSA,R=301]
```

2020-05-22 17:20 UTC, krharsh17 commented
Alright, I just applied the changes @MarkEWaite

2020-05-22 17:36 UTC, MarkEWaite approved these changes

2020-05-25 11:08 UTC, olblak approved these changes

2020-05-25 11:09 UTC, olblak approved these changes

2020-05-25 11:14 UTC, merged

2020-05-25 11:15 UTC, markjacksonfishing approved these changes