Redirect 'Offline Jenkins Installation' to www.jenkins.io
jenkins-infra/jenkins-infra pull request #1513
Opened 2020-06-23 22:48 UTC by MarkEWaite

2020-06-23 23:07 UTC, markjacksonfishing approved these changes

2020-06-24 09:15 UTC, olblak requested changes
RewriteCond is duplicated

2020-06-24 22:52 UTC, MarkEWaite commented
> RewriteCond is duplicated

Resolved in 8ac59e1585957286d9b9af75e7b153bc19e3ef64

2020-06-25 09:17 UTC, olblak approved these changes

2020-06-25 09:18 UTC, merged