Update missing redirects
jenkins-infra/jenkins-infra pull request #1533
Opened 2020-08-15 17:31 UTC by getJv

Update missing redirects from:
* [#3193](https://github.com/jenkins-infra/jenkins.io/issues/3193)
* [#3200](https://github.com/jenkins-infra/jenkins.io/issues/3200)
* [#3322](https://github.com/jenkins-infra/jenkins.io/issues/3322)
* [#3357](https://github.com/jenkins-infra/jenkins.io/issues/3357)
* [#3204](https://github.com/jenkins-infra/jenkins.io/issues/3204)

2020-08-15 18:14 UTC, MarkEWaite requested changes
Thanks for the proposal!  The using local language redirect can point to the specific page.  The JenkinsBehindProxy page is not ready to be redirected because its content has not been migrated to jenkins.io

2020-08-15 18:14 UTC, MarkEWaite commented on dist/profile/templates/confluence/vhost.conf
> +RewriteRule "^/display/JENKINS/How\+to\+view\+Jenkins\+in\+your\+language$" "https://www.jenkins.io/doc/book/using" [NE,NC,L,QSA,R=301]
I think we should directory them to the page that is specific to using Jenkins with a local language.
```suggestion
RewriteRule "^/display/JENKINS/How\+to\+view\+Jenkins\+in\+your\+language$" "https://www.jenkins.io/doc/book/using/using-local-language/" [NE,NC,L,QSA,R=301]
```

2020-08-15 18:14 UTC, MarkEWaite commented on dist/profile/templates/confluence/vhost.conf
> +RewriteRule "^/display/JENKINS/JenkinsBehindProxy$" "https://www.jenkins.io/doc/book/system-administration/reverse-proxy-configuration-with-jenkins" [NE,NC,L,QSA,R=301]
JenkinBehindProxy is not the same as Jenkins behind a reverse proxy.  Jenkins behind a proxy is describing the case where a user is insulated from the public internet by a proxy server that acts on their behalf to access the public internet.  The reverse proxy cases use an HTTP / HTTPS server to host, protect, and defend a Jenkins server.
```suggestion
```

2020-08-17 22:14 UTC, MarkEWaite approved these changes

2020-08-31 03:01 UTC, MarkEWaite approved these changes

2020-08-31 07:34 UTC, markjacksonfishing approved these changes

2020-08-31 12:46 UTC, merged