Update vhost.conf
jenkins-infra/jenkins-infra pull request #1555
Opened 2020-10-04 19:05 UTC by d-schaffer

Redirect 'Writing an SCM plugin' from wiki to docs site #3794

2020-10-04 22:33 UTC, markyjackson-taulia approved these changes

2020-10-05 02:14 UTC, MarkEWaite requested changes
Destination page does not exist.  Please do not merge this change until the destination page exists

2020-10-05 02:16 UTC, MarkEWaite commented on dist/profile/templates/confluence/vhost.conf
> +RewriteRule "^/display/JENKINS/Writinng\+an\+SCM\+plugin$" "https://plugins.jenkins.io/doc/developer/plugin-development/writing-an-scm-plugin" [NC,L,QSA,R=301]
Sorry I missed the actual error on my first review.  The redirect needs to go to the www.jenkins.io page not the plugins.jenkins.io page.
```suggestion
RewriteRule "^/display/JENKINS/Writinng\+an\+SCM\+plugin$" "https://www.jenkins.io/doc/developer/plugin-development/writing-an-scm-plugin" [NC,L,QSA,R=301]
```

2020-10-05 02:24 UTC, MarkEWaite approved these changes

2020-10-05 12:13 UTC, olblak commented on dist/profile/templates/confluence/vhost.conf
> +RewriteCond %{HTTP_USER_AGENT} !^jenkins-wiki-exporter/(.*)$
Duplicated
```suggestion
```

2020-10-05 12:26 UTC, merged