Redirect sublicense and approved usages to www.jenkins.io
jenkins-infra/jenkins-infra pull request #1576
Opened 2020-10-15 04:39 UTC by MarkEWaite

## Redirect sublicense and approved usages to www.jenkins.io

Needs https://github.com/jenkins-infra/jenkins.io/pull/3869 before this is merged.

2020-10-15 05:02 UTC, markyjackson-taulia approved these changes

2020-10-15 07:53 UTC, olblak approved these changes

2020-10-15 07:55 UTC, olblak requested changes
Both redirection redirect to pages that do not exist on jenkins.io

2020-10-15 07:56 UTC, olblak commented
Also it would be nice to start using 'www.jenkins.io' instead of 'jenkins.io'

2020-10-22 19:38 UTC, MarkEWaite commented
@olblak the final destination pages were merged as part of https://github.com/jenkins-infra/jenkins.io/pull/3869 .  I've updated the pull request to use www.jenkins.io and the final destination URLs.

2020-11-17 11:15 UTC, olblak approved these changes

2020-11-17 11:19 UTC, olblak commented
@MarkEWaite  It appears that the vhost check doesn't pass

2021-01-15 09:42 UTC, oleg-nenashev commented on dist/profile/templates/confluence/vhost.conf
> +RewriteRule "^/display/JENKINS/Trademark+Sublicense$" "https://www.jenkins.io/project/trademark/sublicense/" [NC,L,QSA,R=301]
```suggestion
RewriteRule "^/display/JENKINS/Trademark\+Sublicense$" "https://www.jenkins.io/project/trademark/sublicense/" [NC,L,QSA,R=301]
```

2021-01-15 10:08 UTC, olblak approved these changes

2021-01-15 10:09 UTC, merged