Update updatecli github action used
jenkins-infra/jenkins-infra pull request #2059
Opened 2022-02-10 12:53 UTC by olblak

Let switch to the github action

2022-02-10 12:55 UTC, lemeurherve commented
How about including it in [the existing Jenkinsfile](https://github.com/jenkins-infra/jenkins-infra/blob/production/Jenkinsfile) instead?

2022-02-10 13:00 UTC, olblak commented
> How about including it in [the existing Jenkinsfile](https://github.com/jenkins-infra/jenkins-infra/blob/production/Jenkinsfile) instead?

I think that would be even better :)

2022-02-10 13:58 UTC, dduportal commented
That would mean changing agent + 

> How about including it in [the existing Jenkinsfile](https://github.com/jenkins-infra/jenkins-infra/blob/production/Jenkinsfile) instead?

That also means migrating to infra.ci (to have the credentials :))

2022-02-10 14:25 UTC, dduportal commented on .github/workflows/updatecli.yaml
> -        continue-on-error: true
must be kept :)

2022-02-10 14:43 UTC, dduportal commented on .github/workflows/updatecli.yaml
> -          private_key: ${{ secrets.JENKINS_ADMIN_APP_PRIVKEY }}
must be kept

2022-02-10 14:43 UTC, dduportal commented on .github/workflows/updatecli.yaml
> -          UPDATECLI_GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
Must be kept

2022-02-10 14:46 UTC, dduportal requested changes
https://github.com/jenkins-infra/jenkins-infra/blob/production/updatecli/weekly.d/docker-ce.yaml#L21 => require docker CE, which is not present in the updatecli's action.


One solution is a feature request on the updatecli-action (ref. https://github.com/updatecli/updatecli-action/issues/21): allow the action to take care of the updatecli install in the current context.

Another idea from @lemeurherve : allows to use a custom Docker image (but won't solve the Docker CE in Docker problem here)

2022-02-10 14:58 UTC, timja commented
Imo update cli should just have another action, `setup-updatecli`  which installs update cli.
GitHub actions tend to have a lot of tools installed on the agent / you can add more easily there

2022-02-11 18:19 UTC, dduportal commented
Closing this one as we are working on stepping out of GitHub actions for running updatecli (and use our own Jenkins controller, now that it's good enough)

2022-02-11 18:19 UTC, closed without merging