chore (updatecli): create a Jenkinsfile_updatecli to replace github-action
jenkins-infra/jenkins-infra pull request #2673
Opened 2023-03-02 10:10 UTC by smerle33

as per https://github.com/jenkins-infra/jenkins-infra/issues/2393
this depend on the PR adding the folder in kubernet management on infra.ci like : https://github.com/jenkins-infra/kubernetes-management/blob/1ee4ea721c8285c7bd28e3518d835f0e3b045ca2/config/ext_jenkins-infra-jobs.yaml#L152

2023-03-02 10:23 UTC, smerle33 commented
this PR should be merged before https://github.com/jenkins-infra/kubernetes-management/pull/3648 in order to have the jenkins file in the repository before.

2023-03-02 12:31 UTC, MarkEWaite approved these changes, later dismissed
Ugh, I used my command line approval script on the wrong pull request.  Apologies for the unintended approval

2023-03-02 15:58 UTC, lemeurherve submitted a review, later dismissed

2023-03-07 13:40 UTC, lemeurherve reviewed
The files https://github.com/jenkins-infra/jenkins-infra/blob/production/.github/workflows/updatecli.yaml and https://github.com/jenkins-infra/jenkins-infra/blob/production/updatecli/values.github-action.yaml should be deleted in this PR too.

2023-03-07 13:40 UTC, lemeurherve commented on Jenkinsfile_updatecli
> +          sh 'updatecli version'
```suggestion
```
Already in the previous stage

2023-03-07 13:42 UTC, lemeurherve commented
I'm curious, why calling updatecli directly instead of using the `updatecli` shared pipeline library function?

2023-03-07 16:15 UTC, smerle33 commented
> The files https://github.com/jenkins-infra/jenkins-infra/blob/production/.github/workflows/updatecli.yaml and https://github.com/jenkins-infra/jenkins-infra/blob/production/updatecli/values.github-action.yaml should be deleted in this PR too.

I plan it on another PR after this one is merged and the builds are ok on the production branch

2023-03-07 16:16 UTC, smerle33 commented
> I'm curious, why calling updatecli directly instead of using the `updatecli` shared pipeline library function?

because we need a `docker` command ... so using a VM ... and the current version of the shared pipeline library imply using a pod ... so no docker inside.

2023-03-07 17:19 UTC, dduportal commented on Jenkinsfile_updatecli
> +  agent { label 'linux-amd64-docker' }
```suggestion
  // `docker` and `updatecli` are required
  agent { label 'linux-amd64-docker' }
```

nitpick: adding a comment to write down the constraint

2023-03-07 17:22 UTC, dduportal requested changes
Nice job. LGTM, except that you have to remove the `catchError` for the apply part.

2023-03-07 17:22 UTC, dduportal commented on Jenkinsfile_updatecli
> +        catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
```suggestion
```

Blocking: if the "updatecli apply" step fails, then the pipeline must fail. The `catchError()` is only for `updatecli diff` to handle cases where a new code needs to be merged on the principal branch before updatecli can handle it.

2023-03-07 17:22 UTC, dduportal commented on Jenkinsfile_updatecli
> +        }
```suggestion
```

this change is coupled with removing the `cathcError` for apply

2023-03-08 17:42 UTC, dduportal approved these changes
LGTM 👍 Let's merge and see how it behaves

2023-03-08 17:42 UTC, merged