feat(jdk21): add the tooling installation for jdk21 beta
jenkins-infra/jenkins-infra pull request #3003
Opened 2023-08-10 08:05 UTC by smerle33

as per https://github.com/jenkins-infra/helpdesk/issues/3709

2023-08-10 13:59 UTC, timja submitted a review, later dismissed

2023-08-10 14:02 UTC, lemeurherve approved these changes, later dismissed
Some nits, LGTM

2023-08-10 14:02 UTC, lemeurherve commented on README.md
> +You can re-run puppet and execute tests with `vagrant provision ROLE` repeatedly while the VM is up and running or `vagrant up jenkins::controller --provision
```suggestion
You can re-run puppet and execute tests with `vagrant provision ROLE` repeatedly while the VM is up and running, or `vagrant up jenkins::controller --provision`
```

2023-08-10 14:02 UTC, lemeurherve commented on dist/profile/templates/jenkinscontroller/casc/tools.yaml.erb
> +              # Example of subdirs for adoptium 8: jdk8u345-b01, adoptium 11: jdk-11.0.16+8, adoptium 17: jdk-17.0.4+8, adoptium 19: jdk-19.0.1+10, adoptium 21: jdk-2023-08-09-06-56-beta ...
```suggestion
              # Example of subdirs for adoptium 8: jdk8u345-b01, adoptium 11: jdk-11.0.16+8, adoptium 17: jdk-17.0.4+8, adoptium 19: jdk-19.0.1+10, adoptium 21: jdk-2023-08-09-06-56-beta
```

2023-08-10 15:05 UTC, smerle33 commented on README.md
> +You can re-run puppet and execute tests with `vagrant provision ROLE` repeatedly while the VM is up and running or `vagrant up jenkins::controller --provision
this change was useless so I removed it

2023-08-10 15:05 UTC, smerle33 commented on dist/profile/templates/jenkinscontroller/casc/tools.yaml.erb
> +              # Example of subdirs for adoptium 8: jdk8u345-b01, adoptium 11: jdk-11.0.16+8, adoptium 17: jdk-17.0.4+8, adoptium 19: jdk-19.0.1+10, adoptium 21: jdk-2023-08-09-06-56-beta ...
this path was wrong

2023-08-10 15:08 UTC, smerle33 commented
after a pair programming with @dduportal I moved the version definition for jdk21 to the installer part, as long as it's a beta. The name differ without a `-` and a `beta` in the path ... also the zip file main folder is jdk-21+34 and will probably change over time so better to keep it in the installer tools area vs the `tools_default_versions`

2023-08-10 15:16 UTC, dduportal requested changes
2 blockers:

- Don't forget the subdir on all installation kinds
- Vagrant's hieradata is like ci.j's hieradata: it inherits from the `hieradata/common`: no need to re-define the amd64 linux and windows. But I've added linux arm64 to allow testing on apple silicon (+ inheriting from the amd64 from parent common)

2023-08-10 15:16 UTC, dduportal commented on hieradata/clients/controller.ci.jenkins.io.yaml
> +            label: "linux && arm64"
```suggestion
            label: "linux && arm64"
            subdir: "jdk-21+34"
```

2023-08-10 15:16 UTC, dduportal commented on hieradata/clients/controller.ci.jenkins.io.yaml
> +            label: "s390x"
```suggestion
            label: "s390x"
            subdir: "jdk-21+34"
```

2023-08-10 15:16 UTC, dduportal commented on hieradata/vagrant/common.yaml
> +            label: "linux && amd64"
```suggestion
          linux-arm64:
            type: "zip"
            label: "linux && arm64"
            subdir: "jdk-21+34"
            version: "21-2023-08-09-06-56-beta"
```

2023-08-10 15:16 UTC, dduportal commented on hieradata/vagrant/common.yaml
> +            os: "windows"
```suggestion
```

2023-08-11 12:41 UTC, dduportal approved these changes

2023-08-11 13:15 UTC, merged