feat(cert.ci): Added Azure VM templates for Ubuntu-22 jdk-17 and jdk-21
jenkins-infra/jenkins-infra pull request #3565
Opened 2024-07-31 14:15 UTC by jayfranco999

As per https://github.com/jenkins-infra/helpdesk/issues/4124#issue-2335345048:

Added jdk-17 and jdk-21 ssh agents to cert.ci, Ubuntu-22 template will have jdk-11 by deafult.

2024-07-31 17:23 UTC, dduportal requested changes
Great work! but see https://github.com/jenkins-infra/jenkins-infra/pull/3564#pullrequestreview-2210739897

2024-08-08 08:25 UTC, jayfranco999 commented on hieradata/clients/controller.cert.ci.jenkins.io.yaml
> +          maxInstances: 7
```suggestion
          maxInstances: 10
```

2024-08-08 08:25 UTC, jayfranco999 commented on hieradata/clients/controller.cert.ci.jenkins.io.yaml
> +          maxInstances: 7
```suggestion
          maxInstances: 10
```

2024-08-08 08:25 UTC, jayfranco999 commented on hieradata/clients/controller.cert.ci.jenkins.io.yaml
> +          maxInstances: 7
```suggestion
          maxInstances: 10
```

2024-08-08 08:27 UTC, jayfranco999 commented on hieradata/clients/controller.cert.ci.jenkins.io.yaml
> +          javaHome: '/opt/jdk-11'
```suggestion
```

2024-08-08 09:16 UTC, dduportal commented on hieradata/clients/controller.cert.ci.jenkins.io.yaml
> +          maxInstances: 7
```suggestion
          maxInstances: 10 # Quota of 80 vCPUs
```

2024-08-08 09:16 UTC, dduportal commented on hieradata/clients/controller.cert.ci.jenkins.io.yaml
> +          credentialsId: "azure-jenkins-user"
```suggestion
          credentialsId: "azure-login"
```

2024-08-08 09:17 UTC, dduportal commented on hieradata/clients/controller.cert.ci.jenkins.io.yaml
> +          credentialsId: "azure-jenkins-user"
```suggestion
          credentialsId: "azure-login"
```

2024-08-08 09:17 UTC, dduportal commented on hieradata/clients/controller.cert.ci.jenkins.io.yaml
> +          credentialsId: "azure-jenkins-user"
```suggestion
          credentialsId: "azure-login"
```

2024-08-08 09:56 UTC, dduportal approved these changes

2024-08-08 10:13 UTC, merged