feat(trusted.ci): Added Azure VM templates for Ubuntu-22 jdk-17 and jdk-21
jenkins-infra/jenkins-infra pull request #3566
Opened 2024-07-31 14:17 UTC by jayfranco999

As per https://github.com/jenkins-infra/helpdesk/issues/4124#issue-2335345048:

Added jdk-17 and jdk-21 ssh agents to trusted.ci, Ubuntu-22 template will have jdk-11 by deafult.

2024-07-31 17:23 UTC, dduportal requested changes
Great work! but see https://github.com/jenkins-infra/jenkins-infra/pull/3564#pullrequestreview-2210739897

2024-08-08 10:43 UTC, dduportal commented
Ping @jayfranco999 you may rebase and update this PR based on https://github.com/jenkins-infra/helpdesk/issues/4124#issuecomment-2275506395

2024-08-09 07:30 UTC, jayfranco999 commented on hieradata/clients/controller.trusted.ci.jenkins.io.yaml
> +            - ubuntu
```suggestion
            - ubuntu
            - ubuntu-22
```

2024-08-09 07:32 UTC, dduportal approved these changes

2024-08-09 07:37 UTC, merged