[WIP][INFRA-1131] Run Ldap on Kubernetes
jenkins-infra/jenkins-infra pull request #943
Opened 2017-12-14 13:14 UTC by olblak

To Do:
- [ ] Ldap container build from repo [jenkins-infra/ldap](https://github.com/jenkins-infra/ldap)
- [ ] Ldap Backup/Restore process
- [ ] Validate SSL certificate configuration (Letsencrypt? *)
- [ ] Validate Firewall rules
- [ ] Healthcheck should query ldap database
- [ ] Tests
- [ ] Fixed public IP from repo [jenkins-infra/azure](https://github.com/jenkins-infra/azure) 

* We need a way to dynamically reload configuration if certificate changed (every 3 months)

2017-12-15 21:48 UTC, rtyler commented
@olblak I'll take a look at this once it's no longer a WIP

2018-01-13 01:57 UTC, jenkinsadmin commented
The context from the [Jenkins Pipeline run](https://ci.jenkins.io/job/Infra/job/jenkins-infra/job/PR-943/5/display/redirect) is:
```
  should contain Class[profile::apachemisc]
  behaves like it has webserver firewall rules
    should contain Firewall[201 allow https] with action => "accept" and port => 443
    should contain Firewall[200 allow http] with action => "accept" and port => 80

profile::letsencrypt
  should create a cron for updating domains and apache certs
  should contain Class[letsencrypt]
  should use a staging host for letsencrypt

Finished in 28.94 seconds (files took 1.42 seconds to load)
68 examples, 0 failures

Randomized with seed 44584

    should obtain certificates

Finished in 30.73 seconds (files took 1.44 seconds to load)
70 examples, 0 failures

Randomized with seed 11543

Tests Failed

526 examples, 1 failure

Took 32 seconds
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
$ docker stop --time=1 93542bf74d83809d11fe2ff1f155b80e758a3136a72cb83a563d038ac3f027e4
$ docker rm -f 93542bf74d83809d11fe2ff1f155b80e758a3136a72cb83a563d038ac3f027e4
[Pipeline] // withDockerContainer
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] }
[Pipeline] // timeout
[Pipeline] End of Pipeline

GitHub has been notified of this commit’s build result

ERROR: script returned exit code 1
Finished: FAILURE

```
[powered by the Comment Logger](https://github.com/jenkins-infra/community-functions/tree/master/comment-logger)

2018-01-17 02:04 UTC, jenkinsadmin commented
The context from the [Jenkins Pipeline run](https://ci.jenkins.io/job/Infra/job/jenkins-infra/job/PR-943/6/display/redirect) is:
```

  should contain Class[profile::buildslave]
  should contain Class[profile::base]
  on Mac OS X
    should contain a modified buildslave profile

profile::archives
  should contain Class[apache]
  should contain Class[profile::apachemisc]
  should contain Package[httpd] with name => "apache2"
  should contain Apache::Mod[bw]
  should contain Apache::Vhost[archives.jenkins-ci.org]
  should contain Class[lvm]
  behaves like it has webserver firewall rules
    should contain Firewall[201 allow https] with action => "accept" and port => 443
    should contain Firewall[200 allow http] with action => "accept" and port => 80

Finished in 30.44 seconds (files took 1.44 seconds to load)
70 examples, 0 failures

Randomized with seed 45358

Tests Failed

561 examples, 1 failure

Took 32 seconds
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
$ docker stop --time=1 04128f26d42999fc4557828d3fc0fe5600fff7c22bd7b26ada4a876da1e4ce15
$ docker rm -f 04128f26d42999fc4557828d3fc0fe5600fff7c22bd7b26ada4a876da1e4ce15
[Pipeline] // withDockerContainer
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] }
[Pipeline] // timeout
[Pipeline] End of Pipeline

GitHub has been notified of this commit’s build result

ERROR: script returned exit code 1
Finished: FAILURE

```
[powered by the Comment Logger](https://github.com/jenkins-infra/community-functions/tree/master/comment-logger)

2018-01-19 02:08 UTC, jenkinsadmin commented
The context from the [Jenkins Pipeline run](https://ci.jenkins.io/job/Infra/job/jenkins-infra/job/PR-943/7/display/redirect) is:
```
/home/jenkins/workspace/Infra_jenkins-infra_PR-943-TWGGGGV2JKTTTGH5UQJFVJG4UWIOWMPAOS6CU4LA27UCG2IXOHAQ/spec/fixtures/modules/openldap/lib/puppet/provider/openldap_database/olc.rb:8: warning: key :osfamily is duplicated and overwritten on line 8
/home/jenkins/workspace/Infra_jenkins-infra_PR-943-TWGGGGV2JKTTTGH5UQJFVJG4UWIOWMPAOS6CU4LA27UCG2IXOHAQ/spec/fixtures/modules/openldap/lib/puppet/provider/openldap_access/olc.rb:7: warning: key :osfamily is duplicated and overwritten on line 7
/home/jenkins/workspace/Infra_jenkins-infra_PR-943-TWGGGGV2JKTTTGH5UQJFVJG4UWIOWMPAOS6CU4LA27UCG2IXOHAQ/spec/fixtures/modules/openldap/lib/puppet/provider/openldap_dbindex/olc.rb:7: warning: key :osfamily is duplicated and overwritten on line 7
  should contain Class[profile::ldap]
  should contain Class[profile::base]

Finished in 31.05 seconds (files took 1.53 seconds to load)
68 examples, 0 failures

Randomized with seed 39998

  should contain Class[profile::diagnostics]
  should contain Class[jenkins]
  should contain Class[profile::buildmaster]
  should contain Class[firewall]
  should contain Class[profile::base]

Finished in 32.73 seconds (files took 1.46 seconds to load)
70 examples, 0 failures

Randomized with seed 18480

Tests Failed

550 examples, 1 failure

Took 34 seconds
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
$ docker stop --time=1 47c8433ffafd5e60159c2c6654cc315c36139d18c7a42b4f90bed4ef98b033ae
$ docker rm -f 47c8433ffafd5e60159c2c6654cc315c36139d18c7a42b4f90bed4ef98b033ae
[Pipeline] // withDockerContainer
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] }
[Pipeline] // timeout
[Pipeline] End of Pipeline

GitHub has been notified of this commit’s build result

ERROR: script returned exit code 1
Finished: FAILURE

```
[powered by the Comment Logger](https://github.com/jenkins-infra/community-functions/tree/master/comment-logger)

2018-01-24 01:59 UTC, jenkinsadmin commented
The context from the [Jenkins Pipeline run](https://ci.jenkins.io/job/Infra/job/jenkins-infra/job/PR-943/8/display/redirect) is:
```
  should contain Class[profile::kubernetes::kubectl]
  should contain Class[profile::kubernetes::resources::nginx]
  should contain File[/home/k8s/resources/minikube/accountapp] with ensure => "directory" and owner => "k8s"
  should contain Profile::Kubernetes::Apply[accountapp/ingress-tls.yaml on minikube]
  should contain Profile::Kubernetes::Reload[accountapp pods on minikube]
  should contain Profile::Kubernetes::Apply[accountapp/secret.yaml on minikube] with context => "minikube" and parameters => {"ldap_password"=>"bGRhcF9wYXNzd29yZA==", "jira_password"=>"amlyYV9wYXNzd29yZA==", "smtp_password"=>"c210cF9wYXNzd29yZA==", "storage_account_name"=>"aW5mcmF0ZXN0YWNjb3VudGFwcF9uYW1l", "storage_account_key"=>"aW5mcmF0ZXN0YWNjb3VudGFwcF9rZXk="}
  should contain Profile::Kubernetes::Apply[accountapp/service.yaml on minikube]
  should contain Profile::Kubernetes::Apply[accountapp/deployment.yaml on minikube] with context => "minikube" and parameters => {"election_close"=>"2038-01-19", "election_open"=>"1970-01-01", "election_logdir"=>"/var/log/accountapp/elections", "election_candidates"=>"bob,alice", "image_tag"=>"latest", "jira_username"=>"accountapp", "jira_url"=>"https://issues.jenkins-ci.test", "ldap_url"=>"ldap://ldap.jenkins-ci.test", "ldap_manager_dn"=>"cn=admin,dc=jenkins-ci,dc=org", "ldap_new_user_base_dn"=>"ou=people,dc=jenkins-ci,dc=org", "seats"=>"2", "seniority"=>"12", "smtp_server"=>"smtp.jenkins.test", "smtp_user"=>"smtp_user", "smtp_auth"=>true, "url"=>"https://accounts.jenkins.test/"}

role::edamame
  should contain Class[profile::bind]
  should contain Class[profile::robobutler]
  should contain Class[profile::sudo::osu]
  it should behave like a standard role
    should contain Class[profile::base]
    should contain Class[profile::firewall]

Finished in 34.32 seconds (files took 1.44 seconds to load)
72 examples, 0 failures

Randomized with seed 51756

Tests Failed

534 examples, 1 failure

Took 36 seconds
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
$ docker stop --time=1 c3b97d895ceced087e58eb90b6ed045710fe6ce7c8c6c98927b207af23633e00
$ docker rm -f c3b97d895ceced087e58eb90b6ed045710fe6ce7c8c6c98927b207af23633e00
[Pipeline] // withDockerContainer
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] }
[Pipeline] // timeout
[Pipeline] End of Pipeline

GitHub has been notified of this commit’s build result

ERROR: script returned exit code 1
Finished: FAILURE

```
[powered by the Comment Logger](https://github.com/jenkins-infra/community-functions/tree/master/comment-logger)

2018-01-26 02:06 UTC, jenkinsadmin commented
The context from the [Jenkins Pipeline run](https://ci.jenkins.io/job/Infra/job/jenkins-infra/job/PR-943/9/display/redirect) is:
```
  should contain Package[httpd] with name => "apache2"
  should contain Apache::Vhost[archives.jenkins-ci.org]
  should contain Class[profile::apachemisc]
  behaves like it has webserver firewall rules
    should contain Firewall[201 allow https] with action => "accept" and port => 443
    should contain Firewall[200 allow http] with action => "accept" and port => 80

role::mirrorbrain
/home/jenkins/workspace/Infra_jenkins-infra_PR-943-TWGGGGV2JKTTTGH5UQJFVJG4UWIOWMPAOS6CU4LA27UCG2IXOHAQ/spec/fixtures/modules/postgresql/lib/puppet/parser/functions/postgresql_acls_to_resources_hash.rb:33: warning: constant ::Fixnum is deprecated
  should contain Class[profile::mirrorbrain]
  should contain Class[profile::base]
  should contain Class[profile::pkgrepo]
  should contain Class[profile::updatesite]
  it should behave like a standard role
    should contain Class[profile::base]
    should contain Class[profile::firewall]

Finished in 32.95 seconds (files took 1.42 seconds to load)
72 examples, 0 failures

Randomized with seed 59782

Tests Failed

550 examples, 1 failure

Took 35 seconds
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
$ docker stop --time=1 3a89673ed6ea576ebf62d00cadab998ef9b860cf80e181caf3f3609fcd14109a
$ docker rm -f 3a89673ed6ea576ebf62d00cadab998ef9b860cf80e181caf3f3609fcd14109a
[Pipeline] // withDockerContainer
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] }
[Pipeline] // timeout
[Pipeline] End of Pipeline

GitHub has been notified of this commit’s build result

ERROR: script returned exit code 1
Finished: FAILURE

```
[powered by the Comment Logger](https://github.com/jenkins-infra/community-functions/tree/master/comment-logger)

2018-03-13 09:33 UTC, jenkinsadmin commented
Build failed; the context from the [latest run](https://ci.jenkins.io/job/Infra/job/jenkins-infra/job/PR-943/21/display/redirect) is:
<details><summary>Expand to view</summary>

```

Randomized with seed 64536

  should contain Class[profile::robobutler]
  should contain Class[profile::bind]
  should contain Class[profile::sudo::osu]
  it should behave like a standard role
    should contain Class[profile::firewall]
    should contain Class[profile::base]

profile::census::agent
  should contain Class[stdlib]
  should have the usage public key
  should have the usage private key
  should contain Class[profile::census::agent]
  should concat ~/.ssh/config

Finished in 30.4 seconds (files took 1.45 seconds to load)
63 examples, 0 failures

Randomized with seed 33056

Tests Failed

555 examples, 1 failure

Took 32 seconds
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
$ docker stop --time=1 eaf59fbf2d28776540b01b8ce4e2c7df66bf9d0f3fb77a6eb9dcca6af33c37cb
$ docker rm -f eaf59fbf2d28776540b01b8ce4e2c7df66bf9d0f3fb77a6eb9dcca6af33c37cb
[Pipeline] // withDockerContainer
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] }
[Pipeline] // timeout
[Pipeline] End of Pipeline

GitHub has been notified of this commit’s build result

ERROR: script returned exit code 1
Finished: FAILURE

```
</details>

[Powered by the Comment Logger](https://github.com/jenkins-infra/community-functions/tree/master/comment-logger)

2018-03-15 12:39 UTC, jenkinsadmin commented
Build failed; the context from the [latest run](https://ci.jenkins.io/job/Infra/job/jenkins-infra/job/PR-943/22/display/redirect) is:
<details><summary>Expand to view</summary>

```

  should contain Class[profile::kubernetes::params]
  should contain Exec[init nginx/deployment.yaml on minikube] with command => "kubectl apply --context minikube -f /home/k8s/resources/minikube/nginx/deployment.yaml", path => ["/home/k8s/.bin", "/usr/bin"] and onlyif => "test \"$(kubectl apply --dry-run --context minikube -f /home/k8s/resources/minikube/nginx/deployment.yaml | grep created)\""
  should contain Exec[update nginx/deployment.yaml on minikube] with command => "kubectl apply --context minikube -f /home/k8s/resources/minikube/nginx/deployment.yaml", path => ["/home/k8s/.bin", "/usr/bin"] and onlyif => "test \"$(kubectl apply --dry-run --context minikube -f /home/k8s/resources/minikube/nginx/deployment.yaml | grep configured)\""
  should contain File[/home/k8s/resources/minikube/nginx/deployment.yaml] with owner => "k8s" and ensure => "present"
  should contain File[/home/k8s/trash/minikube.nginx.deployment.yaml] with owner => "k8s" and ensure => "present"
  should contain File[/home/k8s/trash/minikube.nginx.deployment.yaml] with ensure => "absent"

Finished in 0.72407 seconds (files took 1.41 seconds to load)
5 examples, 0 failures

Randomized with seed 47732

  should contain Exec[Remove nginx/deployment.yaml on minikube] with command => "kubectl delete --context minikube --grace-period=60 --ignore-not-found=true -f /home/k8s/trash/minikube.nginx.deployment.yaml", path => ["/home/k8s/.bin", "/usr/bin"] and onlyif => "test \"$(kubectl apply --context minikube --dry-run -f /home/k8s/trash/minikube.nginx.deployment.yaml | grep configured)\""
  should contain File[/home/k8s/resources/minikube/nginx/deployment.yaml] with ensure => "absent"
  should contain Class[profile::kubernetes::params]

Finished in 0.72498 seconds (files took 1.42 seconds to load)
4 examples, 0 failures

Randomized with seed 18322

Tests Failed

13 examples, 1 failure

Took 2 seconds
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
$ docker stop --time=1 7e51a12e2114e75abbbba9de4753b13193422e0275712a96f48c37aa42fe052a
$ docker rm -f 7e51a12e2114e75abbbba9de4753b13193422e0275712a96f48c37aa42fe052a
[Pipeline] // withDockerContainer
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] }
[Pipeline] // timeout
[Pipeline] End of Pipeline

GitHub has been notified of this commit’s build result

ERROR: script returned exit code 1
Finished: FAILURE

```
</details>

[Powered by the Comment Logger](https://github.com/jenkins-infra/community-functions/tree/master/comment-logger)

2018-03-15 13:40 UTC, jenkinsadmin commented
Build failed; the context from the [latest run](https://ci.jenkins.io/job/Infra/job/jenkins-infra/job/PR-943/23/display/redirect) is:
<details><summary>Expand to view</summary>

```
[mNotice: Downloading from https://forgeapi.puppet.com ...[0m
[mNotice: Installing -- do not interrupt ...[0m
/home/jenkins/workspace/Infra_jenkins-infra_PR-943-TWGGGGV2JKTTTGH5UQJFVJG4UWIOWMPAOS6CU4LA27UCG2IXOHAQ/spec/fixtures/modules
└── puppet-archive ([0;36mv1.1.2[0m)
[mNotice: Preparing to install into /home/jenkins/workspace/Infra_jenkins-infra_PR-943-TWGGGGV2JKTTTGH5UQJFVJG4UWIOWMPAOS6CU4LA27UCG2IXOHAQ/spec/fixtures/modules ...[0m
[mNotice: Downloading from https://forgeapi.puppet.com ...[0m
[mNotice: Installing -- do not interrupt ...[0m
/home/jenkins/workspace/Infra_jenkins-infra_PR-943-TWGGGGV2JKTTTGH5UQJFVJG4UWIOWMPAOS6CU4LA27UCG2IXOHAQ/spec/fixtures/modules
└── erwbgy-limits ([0;36mv0.3.1[0m)
[mNotice: Preparing to install into /home/jenkins/workspace/Infra_jenkins-infra_PR-943-TWGGGGV2JKTTTGH5UQJFVJG4UWIOWMPAOS6CU4LA27UCG2IXOHAQ/spec/fixtures/modules ...[0m
[mNotice: Downloading from https://forgeapi.puppet.com ...[0m
[mNotice: Installing -- do not interrupt ...[0m
/home/jenkins/workspace/Infra_jenkins-infra_PR-943-TWGGGGV2JKTTTGH5UQJFVJG4UWIOWMPAOS6CU4LA27UCG2IXOHAQ/spec/fixtures/modules
└── puppet-r10k ([0;36mv6.0.0[0m)
[Pipeline] sh
[Infra_jenkins-infra_PR-943-TWGGGGV2JKTTTGH5UQJFVJG4UWIOWMPAOS6CU4LA27UCG2IXOHAQ] Running shell script
+ bundle exec rake lint
`/` is not writable.
Bundler will use `/tmp/bundler/home/unknown' as your home directory temporarily.
dist/profile/manifests/kubernetes/resources/ldap.pp - WARNING: indentation of => is not properly aligned (expected in column 33, but found it in column 32) on line 102
dist/profile/manifests/kubernetes/resources/ldap.pp - WARNING: indentation of => is not properly aligned (expected in column 33, but found it in column 32) on line 103
dist/profile/manifests/kubernetes/resources/ldap.pp - WARNING: indentation of => is not properly aligned (expected in column 33, but found it in column 32) on line 104
dist/profile/manifests/kubernetes/resources/ldap.pp - WARNING: indentation of => is not properly aligned (expected in column 33, but found it in column 32) on line 105
dist/profile/manifests/kubernetes/resources/ldap.pp - WARNING: indentation of => is not properly aligned (expected in column 33, but found it in column 32) on line 106
dist/profile/manifests/kubernetes/resources/ldap.pp - WARNING: indentation of => is not properly aligned (expected in column 33, but found it in column 36) on line 107
dist/profile/manifests/kubernetes/resources/ldap.pp - WARNING: indentation of => is not properly aligned (expected in column 33, but found it in column 36) on line 108
dist/profile/manifests/kubernetes/resources/ldap.pp - WARNING: indentation of => is not properly aligned (expected in column 33, but found it in column 36) on line 109
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
$ docker stop --time=1 a0e78c13a142ab34b6f1977f887c6e746cbfbc3c70b2cd495499278bde0bd36f
$ docker rm -f a0e78c13a142ab34b6f1977f887c6e746cbfbc3c70b2cd495499278bde0bd36f
[Pipeline] // withDockerContainer
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] }
[Pipeline] // timeout
[Pipeline] End of Pipeline

GitHub has been notified of this commit’s build result

ERROR: script returned exit code 1
Finished: FAILURE

```
</details>

[Powered by the Comment Logger](https://github.com/jenkins-infra/community-functions/tree/master/comment-logger)

2018-03-25 02:46 UTC, jenkinsadmin commented
Build failed; the context from the [latest run](https://ci.jenkins.io/job/Infra/job/jenkins-infra/job/PR-943/26/display/redirect) is:
<details><summary>Expand to view</summary>

```
Branch indexing
Connecting to https://api.github.com using jenkinsadmin/****** (GitHub access token for jenkinsadmin)
Connecting to https://api.github.com to check permissions of obtain list of olblak for jenkins-infra/jenkins-infra
Checking out git https://github.com/jenkins-infra/jenkins-infra.git into /var/jenkins_home/jobs/Infra/jobs/jenkins-infra/branches/PR-943/workspace@script to read Jenkinsfile
Fetching changes from the remote Git repository
Fetching without tags
Merging remotes/origin/staging commit 430d0d331b4d6106460a282ff2247c8d6e1dc26f into PR head commit 852b17ac601749da17fcf5b2f26ffa36c39f52b4
Merge succeeded, producing c9e6c22a147f7167ed88a5b3a566bb26f4776aae
Checking out Revision c9e6c22a147f7167ed88a5b3a566bb26f4776aae (PR-943)
Commit message: "Merge commit '430d0d331b4d6106460a282ff2247c8d6e1dc26f' into HEAD"
Running in Durability level: MAX_SURVIVABILITY
Loading library pipeline-library@master
Attempting to resolve master from remote references...
Found match: refs/heads/master revision 7d1d5e7a0561458f33b01b1b25eaf52467723347
Fetching changes from the remote Git repository
Fetching without tags
Checking out Revision 7d1d5e7a0561458f33b01b1b25eaf52467723347 (master)
Commit message: "Merge pull request #27 from daniel-beck/json"
[Pipeline] timeout
Timeout set to expire in 1 hr 0 min
[Pipeline] {
[Pipeline] timestamps
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Verify DNS)
[Pipeline] node
Still waiting to schedule task
Waiting for next available executor on docker
Cancelling nested steps due to timeout
[Pipeline] // node
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Verify Puppet)
Stage 'Verify Puppet' skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] }
[Pipeline] // timeout
[Pipeline] End of Pipeline

GitHub has been notified of this commit’s build result

ERROR: Queue task was cancelled
Finished: FAILURE

```
</details>

[Powered by the Comment Logger](https://github.com/jenkins-infra/community-functions/tree/master/comment-logger)

2018-04-16 12:50 UTC, jenkinsadmin commented
Build failed; the context from the [latest run](https://ci.jenkins.io/job/Infra/job/jenkins-infra/job/PR-943/32/display/redirect) is:
<details><summary>Expand to view</summary>

```
      should contain Apache::Vhost[jenkins-ci.org]
      should be configured to serve over HTTPs

Finished in 30.05 seconds (files took 1.68 seconds to load)
75 examples, 0 failures

Randomized with seed 55205

  should contain Class[profile::puppetagent]
  should contain Profile::Datadog_check[puppetagent-process-check] with checker => "process" and source => "puppet:///modules/profile/puppetagent/process_check.yaml"

role::jenkins::agent
  should contain Class[profile::base]
  should contain Class[profile::buildslave]
  on Mac OS X
    should contain a modified buildslave profile

Finished in 32.4 seconds (files took 1.62 seconds to load)
73 examples, 0 failures

Randomized with seed 43921

Tests Failed

595 examples, 1 failure

Took 34 seconds
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
$ docker stop --time=1 551f03bd2a3c1367cf3a23e532852c0302ec7186fa8f1786b1851982a5c64e7f
$ docker rm -f 551f03bd2a3c1367cf3a23e532852c0302ec7186fa8f1786b1851982a5c64e7f
[Pipeline] // withDockerContainer
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] }
[Pipeline] // timeout
[Pipeline] End of Pipeline

GitHub has been notified of this commit’s build result

ERROR: script returned exit code 1
Finished: FAILURE

```
</details>

[Powered by the Comment Logger](https://github.com/jenkins-infra/community-functions/tree/master/comment-logger)

2018-04-16 13:37 UTC, jenkinsadmin commented
Build failed; the context from the [latest run](https://ci.jenkins.io/job/Infra/job/jenkins-infra/job/PR-943/33/display/redirect) is:
<details><summary>Expand to view</summary>

```
Randomized with seed 57910

      should configure the letsencrypt ssl keys on the vhost
      should contain Letsencrypt::Certonly[rspec.jenkins.io]
  firewall rules
    should allow CLI SSH on 22222
    should contain Class[profile::firewall]
    should ensure nothing talks directly to Jenkins
    should have a CLI port rule

profile::demo
  should contain Class[docker]
  should contain Docker::Run[demo]
  should contain Docker::Image[jenkinsci/jenkins]
  should contain User[demo]
  should contain Service[docker-demo]

Finished in 31.78 seconds (files took 1.6 seconds to load)
73 examples, 0 failures

Randomized with seed 39045

Tests Failed

594 examples, 1 failure

Took 34 seconds
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
$ docker stop --time=1 497ad8ba72f1e1599a826aa97bafd025b60529575563f551b0043d4656e53978
$ docker rm -f 497ad8ba72f1e1599a826aa97bafd025b60529575563f551b0043d4656e53978
[Pipeline] // withDockerContainer
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] }
[Pipeline] // timeout
[Pipeline] End of Pipeline

GitHub has been notified of this commit’s build result

ERROR: script returned exit code 1
Finished: FAILURE

```
</details>

[Powered by the Comment Logger](https://github.com/jenkins-infra/community-functions/tree/master/comment-logger)

2018-04-16 13:47 UTC, jenkinsadmin commented
Build failed; the context from the [latest run](https://ci.jenkins.io/job/Infra/job/jenkins-infra/job/PR-943/34/display/redirect) is:
<details><summary>Expand to view</summary>

```
    should contain Letsencrypt::Certonly[accounts.jenkins.io]

Finished in 29.38 seconds (files took 1.48 seconds to load)
64 examples, 0 failures

Randomized with seed 8591

  should contain Class[jenkins]
  should contain Class[profile::diagnostics]
  should contain Class[profile::base]

role::jenkins::agent
  should contain Class[profile::buildslave]
  should contain Class[profile::base]
  on Mac OS X
    should contain a modified buildslave profile

Finished in 31.17 seconds (files took 1.48 seconds to load)
73 examples, 0 failures

Randomized with seed 35125

Tests Failed

576 examples, 1 failure

Took 33 seconds
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
$ docker stop --time=1 b874279d3d459ef89e9e8e98bdb8901fa52ec50cafd2fa8ac045f3673b7e68a5
$ docker rm -f b874279d3d459ef89e9e8e98bdb8901fa52ec50cafd2fa8ac045f3673b7e68a5
[Pipeline] // withDockerContainer
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] }
[Pipeline] // timeout
[Pipeline] End of Pipeline

GitHub has been notified of this commit’s build result

ERROR: script returned exit code 1
Finished: FAILURE

```
</details>

[Powered by the Comment Logger](https://github.com/jenkins-infra/community-functions/tree/master/comment-logger)

2018-04-16 14:04 UTC, jenkinsadmin commented
Build failed; the context from the [latest run](https://ci.jenkins.io/job/Infra/job/jenkins-infra/job/PR-943/35/display/redirect) is:
<details><summary>Expand to view</summary>

```
    should contain Apache::Vhost[stats.jenkins-ci.org]
    HTTP VirtualHost
      should be configured to promote to a HTTPs request
      should contain Apache::Vhost[jenkins-ci.org unsecured]
    HTTPs VirtualHost
      should contain Apache::Vhost[jenkins-ci.org]
      should be configured to serve over HTTPs

Finished in 29.16 seconds (files took 1.57 seconds to load)
75 examples, 0 failures

Randomized with seed 21833

  should contain Class[role::vhostcatchall]
  should contain Class[profile::base]
  should contain Class[profile::catchall]

Finished in 31.01 seconds (files took 1.51 seconds to load)
73 examples, 0 failures

Randomized with seed 41400

Tests Failed

584 examples, 1 failure

Took 33 seconds
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
$ docker stop --time=1 466336ef40662828f20994f7c66698c0d07ba14f42b6fa8890c829e67382867c
$ docker rm -f 466336ef40662828f20994f7c66698c0d07ba14f42b6fa8890c829e67382867c
[Pipeline] // withDockerContainer
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] }
[Pipeline] // timeout
[Pipeline] End of Pipeline

GitHub has been notified of this commit’s build result

ERROR: script returned exit code 1
Finished: FAILURE

```
</details>

[Powered by the Comment Logger](https://github.com/jenkins-infra/community-functions/tree/master/comment-logger)

2018-04-16 14:07 UTC, jenkinsadmin commented
Build failed; the context from the [latest run](https://ci.jenkins.io/job/Infra/job/jenkins-infra/job/PR-943/36/display/redirect) is:
<details><summary>Expand to view</summary>

```
  should contain Profile::Kubernetes::Apply[fluentd/daemonset.yaml on minikube] with context => "minikube" and parameters => {"image_tag"=>"FFFFFF"}

Finished in 30.09 seconds (files took 1.58 seconds to load)
75 examples, 0 failures

Randomized with seed 6242

  should contain Apache::Mod[bw]
  should contain Apache::Vhost[archives.jenkins-ci.org]
  should contain Class[apache]
  should contain Class[profile::apachemisc]
  should contain Class[lvm]
  should contain Package[httpd] with name => "apache2"
  behaves like it has webserver firewall rules
    should contain Firewall[200 allow http] with action => "accept" and port => 80
    should contain Firewall[201 allow https] with action => "accept" and port => 443

Finished in 31.8 seconds (files took 1.54 seconds to load)
73 examples, 0 failures

Randomized with seed 49463

Tests Failed

569 examples, 1 failure

Took 33 seconds
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
$ docker stop --time=1 1fee8a73157e2a67f210f52788c72d92ec7ed085fb66ce52dd0cb4485894ba12
$ docker rm -f 1fee8a73157e2a67f210f52788c72d92ec7ed085fb66ce52dd0cb4485894ba12
[Pipeline] // withDockerContainer
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] }
[Pipeline] // timeout
[Pipeline] End of Pipeline

GitHub has been notified of this commit’s build result

ERROR: script returned exit code 1
Finished: FAILURE

```
</details>

[Powered by the Comment Logger](https://github.com/jenkins-infra/community-functions/tree/master/comment-logger)

2018-04-16 17:48 UTC, jenkinsadmin commented
Build failed; the context from the [latest run](https://ci.jenkins.io/job/Infra/job/jenkins-infra/job/PR-943/37/display/redirect) is:
<details><summary>Expand to view</summary>

```
  should contain File[/etc/apache2/legacy_cert.key] with ensure => :present
  Apache VirtualHosts
    should contain Apache::Vhost[maven.jenkins-ci.org]
    should contain Apache::Vhost[stats.jenkins-ci.org]
    HTTP VirtualHost
      should be configured to promote to a HTTPs request
      should contain Apache::Vhost[jenkins-ci.org unsecured]
    HTTPs VirtualHost
      should contain Apache::Vhost[jenkins-ci.org]
      should be configured to serve over HTTPs

role::jenkins::agent
  should contain Class[profile::base]
  should contain Class[profile::buildslave]
  on Mac OS X
    should contain a modified buildslave profile

Finished in 31.79 seconds (files took 1.59 seconds to load)
73 examples, 0 failures

Randomized with seed 3149

Tests Failed

530 examples, 1 failure

Took 34 seconds
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
$ docker stop --time=1 751dd8489eb23bafc1ad2674539bd197135396acba5d9cc80f387513d93b8d17
$ docker rm -f 751dd8489eb23bafc1ad2674539bd197135396acba5d9cc80f387513d93b8d17
[Pipeline] // withDockerContainer
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] }
[Pipeline] // timeout
[Pipeline] End of Pipeline

GitHub has been notified of this commit’s build result

ERROR: script returned exit code 1
Finished: FAILURE

```
</details>

[Powered by the Comment Logger](https://github.com/jenkins-infra/community-functions/tree/master/comment-logger)

2018-04-16 19:41 UTC, rtyler approved these changes

2018-04-16 19:41 UTC, rtyler commented on dist/profile/templates/kubernetes/resources/ldap/persistentVolumeClaim-backup.yaml.erb
> +  storageClassName: ""
Will you add a comment on the significance of this so somebody (like me!) doesn't accidentally remove it in the future

2018-04-16 19:41 UTC, rtyler commented on hieradata/env/production.yaml
> +      ldap_public_ip: 52.232.180.203
This looks like hard-coded, can you add a comment where this hard-coded value comes from? Presumably terraform?

2018-04-16 19:41 UTC, rtyler requested changes
bok

2018-04-17 09:51 UTC, olblak commented
You can merge it once approved

2018-04-17 13:14 UTC, rtyler approved these changes

2018-04-17 13:16 UTC, merged